version: '3'
services:
  db:
    image: postgres:11.4-alpine
    container_name: postgres-test
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./data/V1__CreateDB.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./data/V2__InitDB.sql:/docker-entrypoint-initdb.d/2-init.sql
      - ./data/V3__ChangeItemImage.sql:/docker-entrypoint-initdb.d/3-changeBinary.sql
    restart: always
  testAuthService:
    image: vladsmirn289/authentication_service
    container_name: testAuthService
    ports:
      - 8081:8081
    environment:
      db_host: db
    restart: always
    links:
      - db
  testClientService:
    image: vladsmirn289/client_service_rest
    container_name: testClientService
    ports:
      - 8082:8082
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - testAuthService
      - db